version: '3'

silent: true

tasks:

  build:
    desc: Builds this library
    cmds:
      - cmd: rebar3 compile

  clean:
    desc: Removes all generated content
    cmds:
      - cmd: rebar3 clean
      - cmd: rm -rf _build

  cov:
    desc: Generate code coverage report
    cmds:
      - task: clean
      - cmd: rebar3 eunit --cover
      - cmd: rebar3 cover
      - cmd: echo -e "\n\e[1;32mOpen coverage report\x3A\e[0m file:///$(pwd)/_build/test/cover/index.html\n"

  shell:
    desc: Runs a shell with this library as dependencies
    cmds:
      - cmd: rebar3 shell

  test:
    desc: Runs all tests
    cmds:
      - task: clean
      - cmd: rebar3 eunit
